workflows:
  android-workflow: # ou o nome que estiver no seu arquivo
    name: Android Build
    environment:
      groups:
        - firebase # se tiver algum grupo, deixe aqui
      vars:
        # Cole o texto Base64 longo aqui dentro das aspas:
        GOOGLE_SERVICES_JSON: "COLE_AQUI_O_TEXTO_BASE64_LONGO"
      flutter: stable
    scripts:
      - name: Decompress Google Services JSON
        script: |
          mkdir -p android/app
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/google-services.json
      - name: Flutter build
        script: |
          flutter build apk --release
