workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Criar pastas nativas
        script: flutter create . --platforms android,ios

      - name: Gerar ícones do app
        script: dart run flutter_launcher_icons

      - name: Criar google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
